// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGTuNIovUrSWduAinSZWOcH-3akWEhqw',
    appId: '1:38813777969:web:1c1c5b6f065767b91f1510',
    messagingSenderId: '38813777969',
    projectId: 'docdoc-app-distribution-d2c48',
    authDomain: 'docdoc-app-distribution-d2c48.firebaseapp.com',
    storageBucket: 'docdoc-app-distribution-d2c48.firebasestorage.app',
    measurementId: 'G-M013939MY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8mf0LWOJMgK-96xbno7H8BFN0CtP05M4',
    appId: '1:38813777969:android:f0513f30e588c47a1f1510',
    messagingSenderId: '38813777969',
    projectId: 'docdoc-app-distribution-d2c48',
    storageBucket: 'docdoc-app-distribution-d2c48.firebasestorage.app',
  );

}