default_platform(:android)

platform :android do

  desc "Deploy to Firebase App Distribution"
  lane :fb_deploy do
    UI.message("Fetching latest build version from Firebase App Distribution...")
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:38813777969:android:f0513f30e588c47a1f1510",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
    
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    UI.message("Uploading production build to Firebase App Distribution...")
    firebase_app_distribution(
      app: "1:38813777969:android:f0513f30e588c47a1f1510",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"], 
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk", 
      testers: "mohamedmsalah396@gmail.com",
      release_notes: "New Version Published! Ready for Testing! 🧑‍💻" 
    )
  end
end
